In [3]:
import pandas as pd
import numpy as np

In [6]:
# Load the dataset from a CSV file
df = pd.read_csv('ner_datasetreference.csv', encoding='ISO-8859-1')
df.head(20)

Sentence #           Word  POS    Tag
0   Sentence: 1      Thousands  NNS      O
1           NaN             of   IN      O
2           NaN  demonstrators  NNS      O
3           NaN           have  VBP      O
4           NaN        marched  VBN      O
5           NaN        through   IN      O
6           NaN         London  NNP  B-geo
7           NaN             to   TO      O
8           NaN        protest   VB      O
9           NaN            the   DT      O
10          NaN            war   NN      O
11          NaN             in   IN      O
12          NaN           Iraq  NNP  B-geo
13          NaN            and   CC      O
14          NaN         demand   VB      O
15          NaN            the   DT      O
16          NaN     withdrawal   NN      O
17          NaN             of   IN      O
18          NaN        British   JJ  B-gpe
19          NaN         troops  NNS      O

In [7]:
import pandas as pd
import string
from nltk.corpus import stopwords

df['clean_text']=df['Word'].str.lower()

STOPWORDS = set(stopwords.words('english'))
def remove_stopwords(text):
    return " ".join([word for word in text.split() if word not in STOPWORDS])
df['clean_text'] = df['clean_text'].apply(lambda x: remove_stopwords(x))

import re
def remove_spl_chars(text):
    text = re.sub('[^a-zA-Z0-9]', ' ', text)
    text = re.sub('\s+', ' ', text)
    return text
df['clean_text'] = df['clean_text'].apply(lambda x: remove_spl_chars(x))

df.head(20)


Sentence #           Word  POS    Tag     clean_text
0   Sentence: 1      Thousands  NNS      O      thousands
1           NaN             of   IN      O               
2           NaN  demonstrators  NNS      O  demonstrators
3           NaN           have  VBP      O               
4           NaN        marched  VBN      O        marched
5           NaN        through   IN      O               
6           NaN         London  NNP  B-geo         london
7           NaN             to   TO      O               
8           NaN        protest   VB      O        protest
9           NaN            the   DT      O               
10          NaN            war   NN      O            war
11          NaN             in   IN      O               
12          NaN           Iraq  NNP  B-geo           iraq
13          NaN            and   CC      O               
14          NaN         demand   VB      O         demand
15          NaN            the   DT      O               
16          NaN     withdrawal   NN      O     withdrawal
17          NaN             of   IN      O               
18          NaN        British   JJ  B-gpe        british
19          NaN         troops  NNS      O         troops

In [8]:
df['Word'] = df['Word'].apply(lambda x: ''.join(x))

In [9]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf_vect = TfidfVectorizer()
features = tfidf_vect.fit_transform(df['Word'])

In [11]:
pd.DataFrame(features.toarray(),columns = tfidf_vect.vocabulary_.keys())

thousands   of  demonstrators  have  marched  through  london   to  \
0              0.0  0.0            0.0   0.0      0.0      0.0     0.0  0.0   
1              0.0  0.0            0.0   0.0      0.0      0.0     0.0  0.0   
2              0.0  0.0            0.0   0.0      0.0      0.0     0.0  0.0   
3              0.0  0.0            0.0   0.0      0.0      0.0     0.0  0.0   
4              0.0  0.0            0.0   0.0      0.0      0.0     0.0  0.0   
...            ...  ...            ...   ...      ...      ...     ...  ...   
1048570        0.0  0.0            0.0   0.0      0.0      0.0     0.0  0.0   
1048571        0.0  0.0            0.0   0.0      0.0      0.0     0.0  0.0   
1048572        0.0  0.0            0.0   0.0      0.0      0.0     0.0  0.0   
1048573        0.0  0.0            0.0   0.0      0.0      0.0     0.0  0.0   
1048574        0.0  0.0            0.0   0.0      0.0      0.0     0.0  0.0   

         protest  the  ...  coldest  mikulski  shyster  uhstad  thura  mahn  \
0            0.0  0.0  ...      0.0       0.0      0.0     0.0    0.0   0.0   
1            0.0  0.0  ...      0.0       0.0      0.0     0.0    0.0   0.0   
2            0.0  0.0  ...      0.0       0.0      0.0     0.0    0.0   0.0   
3            0.0  0.0  ...      0.0       0.0      0.0     0.0    0.0   0.0   
4            0.0  0.0  ...      0.0       0.0      0.0     0.0    0.0   0.0   
...          ...  ...  ...      ...       ...      ...     ...    ...   ...   
1048570      0.0  0.0  ...      0.0       0.0      0.0     0.0    0.0   0.0   
1048571      0.0  0.0  ...      0.0       0.0      0.0     0.0    0.0   0.0   
1048572      0.0  0.0  ...      0.0       0.0      0.0     0.0    0.0   0.0   
1048573      0.0  0.0  ...      0.0       0.0      0.0     0.0    0.0   0.0   
1048574      0.0  0.0  ...      0.0       0.0      0.0     0.0    0.0   0.0   

         hardliner  indicative  3700  bermel  
0              0.0         0.0   0.0     0.0  
1              0.0         0.0   0.0     0.0  
2              0.0         0.0   0.0     0.0  
3              0.0         0.0   0.0     0.0  
4              0.0         0.0   0.0     0.0  
...            ...         ...   ...     ...  
1048570        0.0         0.0   0.0     0.0  
1048571        0.0         0.0   0.0     0.0  
1048572        0.0         0.0   0.0     0.0  
1048573        0.0         0.0   0.0     0.0  
1048574        0.0         0.0   0.0     0.0  

[1048575 rows x 27889 columns]

In [12]:
#Train test split
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(features, df['Word'], test_size=0.2)


In [13]:
print(X_train.shape)
print(X_test.shape)

(838860, 27889)
(209715, 27889)


In [ ]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(X_train, y_train)

In [ ]:
import numpy as np
# predicted = 0,1
predicted = model.predict(X_test)

# accuracy
print(np.mean(predicted == y_test ))

In [36]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test ,predicted))

#[true negative ,false positive ,false negative ,predicted yes ]



[[  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 ...
 [  0   0  16 ...   0   0   0]
 [  0   0   2 ...   0 405   0]
 [  0   0   0 ...   0   0   0]]


In [27]:
from sklearn.feature_extraction.text import CountVectorizer
count_Vect= CountVectorizer()
features = count_Vect.fit_transform(df['Word'])

In [19]:
pd.DataFrame(features.toarray(),columns = count_Vect.vocabulary_.keys())

thousands  of  demonstrators  have  marched  through  london  to  \
0                0   0              0     0        0        0       0   0   
1                0   0              0     0        0        0       0   0   
2                0   0              0     0        0        0       0   0   
3                0   0              0     0        0        0       0   0   
4                0   0              0     0        0        0       0   0   
...            ...  ..            ...   ...      ...      ...     ...  ..   
1048570          0   0              0     0        0        0       0   0   
1048571          0   0              0     0        0        0       0   0   
1048572          0   0              0     0        0        0       0   0   
1048573          0   0              0     0        0        0       0   0   
1048574          0   0              0     0        0        0       0   0   

         protest  the  ...  coldest  mikulski  shyster  uhstad  thura  mahn  \
0              0    0  ...        0         0        0       0      0     0   
1              0    0  ...        0         0        0       0      0     0   
2              0    0  ...        0         0        0       0      0     0   
3              0    0  ...        0         0        0       0      0     0   
4              0    0  ...        0         0        0       0      0     0   
...          ...  ...  ...      ...       ...      ...     ...    ...   ...   
1048570        0    0  ...        0         0        0       0      0     0   
1048571        0    0  ...        0         0        0       0      0     0   
1048572        0    0  ...        0         0        0       0      0     0   
1048573        0    0  ...        0         0        0       0      0     0   
1048574        0    0  ...        0         0        0       0      0     0   

         hardliner  indicative  3700  bermel  
0                0           0     0       0  
1                0           0     0       0  
2                0           0     0       0  
3                0           0     0       0  
4                0           0     0       0  
...            ...         ...   ...     ...  
1048570          0           0     0       0  
1048571          0           0     0       0  
1048572          0           0     0       0  
1048573          0           0     0       0  
1048574          0           0     0       0  

[1048575 rows x 27889 columns]

In [20]:
#Train test split
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(features, df['POS'], test_size=0.2)


In [21]:
print(X_train.shape)
print(X_test.shape)

(838860, 27889)
(209715, 27889)


In [22]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(X_train, y_train)

MultinomialNB()

In [39]:
import numpy as np
# predicted = 0,1
predicted = model.predict(X_test)

# accuracy
print(np.mean(predicted == y_test ))

0.797115132441647


In [38]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test ,predicted))

#[true negative ,false positive ,false negative ,predicted yes ]

[[  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 ...
 [  0   0  16 ...   0   0   0]
 [  0   0   2 ...   0 405   0]
 [  0   0   0 ...   0   0   0]]
