In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('ner_datasetreference.csv', encoding='ISO-8859-1')
df.head()

Sentence #           Word  POS Tag
0  Sentence: 1      Thousands  NNS   O
1          NaN             of   IN   O
2          NaN  demonstrators  NNS   O
3          NaN           have  VBP   O
4          NaN        marched  VBN   O

In [42]:
#return a Pandas Series with counts of unique words in the 'Word' column 
df['Word'].value_counts()

the         52573
.           47761
,           32754
of          26354
in          26323
            ...  
Dateline        1
ISRO            1
G.              1
Madhavan        1
Bermel          1
Name: Word, Length: 35178, dtype: int64

In [58]:
#create a new column 'Dateline' and set it to 1 for rows where the 'Word' column is equal to 'Dateline' and 0 otherwise
df['Dateline'] = df['Word'].apply(lambda x: 1 if x =='Dateline' else 0)

In [59]:
#number of rows and the number of columns.
df.shape

(1048575, 6)

In [60]:
df.head(20)

Sentence #           Word  POS    Tag  IN  Dateline
0   Sentence: 1      Thousands  NNS      O   0         0
1           NaN             of   IN      O   1         0
2           NaN  demonstrators  NNS      O   0         0
3           NaN           have  VBP      O   0         0
4           NaN        marched  VBN      O   0         0
5           NaN        through   IN      O   1         0
6           NaN         London  NNP  B-geo   0         0
7           NaN             to   TO      O   0         0
8           NaN        protest   VB      O   0         0
9           NaN            the   DT      O   0         0
10          NaN            war   NN      O   0         0
11          NaN             in   IN      O   1         0
12          NaN           Iraq  NNP  B-geo   0         0
13          NaN            and   CC      O   0         0
14          NaN         demand   VB      O   0         0
15          NaN            the   DT      O   0         0
16          NaN     withdrawal   NN      O   0         0
17          NaN             of   IN      O   1         0
18          NaN        British   JJ  B-gpe   0         0
19          NaN         troops  NNS      O   0         0

In [80]:
#Train test split
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df['Word'], df['Dateline'], test_size=0.2)


In [81]:
print(X_train.shape)

(838860,)


In [63]:
X_test.shape

(209715,)

In [64]:
type(X_train)

pandas.core.series.Series

In [65]:
X_train[:4]

487665           are
602821         Sudan
274658    cease-fire
539951    restarting
Name: Word, dtype: object

In [66]:
type(y_train)

pandas.core.series.Series

In [67]:
y_train[:4]

487665    0
602821    0
274658    0
539951    0
Name: IN, dtype: int64

In [68]:
type(X_train.values)

numpy.ndarray

In [69]:
# Create bag of words representation using CountVectorizer
from sklearn.feature_extraction.text import CountVectorizer

v = CountVectorizer()

X_train_cv = v.fit_transform(X_train.values)
X_train_cv


<838860x25709 sparse matrix of type '<class 'numpy.int64'>'
	with 744671 stored elements in Compressed Sparse Row format>

In [70]:
X_train_cv.toarray()[:2][0]

array([0, 0, 0, ..., 0, 0, 0])

In [71]:
X_train_cv.shape

(838860, 25709)

In [72]:
v.get_feature_names_out()[1771]

'ancient'

In [73]:
v.vocabulary_

{'are': 2099,
 'sudan': 22406,
 'cease': 4407,
 'fire': 9026,
 'restarting': 19504,
 'states': 22042,
 'apology': 1969,
 'bowman': 3706,
 '160': 127,
 'an': 1744,
 'aristide': 2131,
 'the': 23170,
 'with': 25233,
 'reporter': 19360,
 'official': 16362,
 'after': 1305,
 'before': 3065,
 'it': 12182,
 'president': 17964,
 'earlier': 7613,
 'tribal': 23705,
 'villagers': 24661,
 'this': 23233,
 'says': 20390,
 'day': 6276,
 'has': 10640,
 'christians': 4789,
 'aging': 1341,
 'trains': 23592,
 'still': 22123,
 'africa': 1296,
 'international': 11980,
 'iraqi': 12102,
 'presidential': 17965,
 'war': 24899,
 'thursday': 23288,
 'early': 7615,
 'justice': 12587,
 'in': 11539,
 'israel': 12167,
 'replace': 19347,
 'ministers': 14984,
 'movement': 15382,
 'where': 25108,
 'final': 8983,
 '1994': 360,
 'they': 23207,
 'exclusive': 8392,
 'ugandan': 23956,
 'friday': 9455,
 'denver': 6598,
 'ordered': 16531,
 'have': 10682,
 'reporters': 19361,
 'aircraft': 1407,
 'were': 25069,
 'there': 23196,


In [74]:
X_train_np = X_train_cv.toarray()
X_train_np[0]

array([0, 0, 0, ..., 0, 0, 0])

In [75]:
np.where(X_train_np[0]!=0)

(array([2099]),)

In [76]:
X_train_np[0][1771]

0

In [77]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(X_train_cv, y_train)

MultinomialNB()

In [78]:
X_test_cv = v.transform(X_test)

In [79]:
from sklearn.metrics import classification_report

import numpy as np
# predicted = 0,1
predicted = model.predict(X_train_cv )

# accuracy
print(np.mean(predicted == y_test ))

/var/folders/mk/0wr72hyx31d9dtn7r75t45y40000gn/T/ipykernel_28590/2000389303.py:8: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  print(np.mean(predicted == y_test ))


ValueError: ('Lengths must match to compare', (209715,), (838860,))